version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container3
    environment:
      POSTGRES_USER: User
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: DatabasePr9
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: